import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import PostListing from "../components/PostListing";

const Home: NextPage = () => {
  const { data, status } = useSession();

  if (status === "unauthenticated") {
    return (
      <div>
        You need to{" "}
        <button
          onClick={() => signIn()}
          className="text-blue-500 underline-offset-1 hover:text-blue-700"
        >
          login
        </button>{" "}
        to create a post
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>T3 Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-center bg-zinc-900">
        <PostListing />
      </main>
    </>
  );
};

export default Home;
