import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import PostListing from "../components/PostListing";

const Home: NextPage = () => {
  const { data, status } = useSession();

  if (status === "unauthenticated") {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-900">
        <div className="text-white">
          You need to{" "}
          <button
            onClick={() => signIn()}
            className="text-blue-500 underline-offset-1 hover:text-blue-700"
          >
            login
          </button>{" "}
          to create a post
        </div>
        <PostListing />
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>T3 Blog</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-zinc-900">
        <div className="flex w-2/4 justify-between gap-2 rounded">
          <Link href="/posts/new">
            <h1 className="hover rounded border p-2 text-white hover:bg-zinc-800">
              Create Post
            </h1>
          </Link>
          <button
            onClick={() => signOut()}
            className="hover rounded border p-2 text-white hover:bg-zinc-800"
          >
            Logout
          </button>
        </div>
        <PostListing />
      </main>
    </>
  );
};

export default Home;
